<a href="https://colab.research.google.com/github/JoyDantas/Estudos_Colab/blob/main/consolidacao_tiktok_historico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
tiktok_itaucard = pd.read_csv('/content/drive/MyDrive/historico - tiktok/TiktokAds_Ad Performance_DPZT _ Itaucard_20210101-20220101.csv', sep=";")
tiktok_institucional = pd.read_csv('/content/drive/MyDrive/historico - tiktok/TiktokAds_Ad Performance_DPZT _ ItauÃÅ Institucional_20210101-20220101.csv', sep=';')
tiktok_mc = pd.read_csv("/content/drive/MyDrive/historico - tiktok/TiktokAds_Ad Performance_DPZT _ McDonald's_20210101-20220101.csv", sep=";")
tiktok_natura = pd.read_csv('/content/drive/MyDrive/historico - tiktok/TiktokAds_Ad Performance_DPZT _ Natura_20210101-20220101.csv', sep=";")

In [ ]:
concat_frames = [tiktok_itaucard, tiktok_institucional, tiktok_mc, tiktok_natura]

In [ ]:
consolidado_tiktok = pd.concat(concat_frames)

In [ ]:
## conferindo formatos
consolidado_tiktok.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45841 entries, 0 to 685
Data columns (total 40 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               45841 non-null  object
 1   Ad ID                              45841 non-null  object
 2   Cliente                            45841 non-null  object
 3   Ad Name                            45841 non-null  object
 4   Ads Format                         45841 non-null  object
 5   Text                               45841 non-null  object
 6   Ad Group ID                        44208 non-null  object
 7   Ad Group Name                      44208 non-null  object
 8   Campaign ID                        44208 non-null  object
 9   Campaign Name                      44208 non-null  object
 10  Placements Types                   44208 non-null  object
 11  Optimization Goal                  44208 non-null  object
 12  Cost                               44208 non-null  float64
 13  CPC                                44208 non-null  float64
 14  CPM                                44208 non-null  float64
 15  Impression                         44208 non-null  float64
 16  Click                              44208 non-null  float64
 17  CTR                                44208 non-null  float64
 18  Frequency                          44208 non-null  float64
 19  Conversions                        44208 non-null  float64
 20  CPA                                44208 non-null  float64
 21  CVR                                44208 non-null  float64
 22  Video Views                        44208 non-null  float64
 23  2-Second Video Views               44208 non-null  float64
 24  6-Second Video Views               44208 non-null  float64
 25  Video Views at 100%                44208 non-null  float64
 26  Video Views at 75%                 44208 non-null  float64
 27  Video Views at 50%                 44208 non-null  float64
 28  Video Views at 25%                 44208 non-null  float64
 29  Average Watch Time per Video View  44208 non-null  float64
 30  Average Watch Time per Person      44208 non-null  float64
 31  Paid Followers                     44208 non-null  float64
 32  Paid Likes                         44208 non-null  float64
 33  Paid Comments                      44208 non-null  float64
 34  Paid Shares                        44208 non-null  float64
 35  Paid Profile Visits                42575 non-null  float64
 36  Paid Profile Visit Rate            42575 non-null  float64
 37  Anchor Clicks                      42575 non-null  float64
 38  Anchor Clicks Rate                 42575 non-null  float64
 39  Clicks on Music Disc               686 non-null    float64
dtypes: float64(28), object(12)
memory usage: 14.3+ MB

In [ ]:
## contando valores null
print(consolidado_tiktok[consolidado_tiktok['Cost'].isnull()])

             Date        Ad ID  ... Anchor Clicks Rate Clicks on Music Disc
21     22/01/2021  1,68961E+15  ...                NaN                  NaN
27     23/01/2021  1,68961E+15  ...                NaN                  NaN
47     24/01/2021  1,68961E+15  ...                NaN                  NaN
61     25/01/2021  1,68961E+15  ...                NaN                  NaN
86     26/01/2021  1,68961E+15  ...                NaN                  NaN
...           ...          ...  ...                ...                  ...
31643  12/09/2021  1,69369E+15  ...                NaN                  NaN
31702  13/09/2021  1,69369E+15  ...                NaN                  NaN
32106  15/09/2021  1,69369E+15  ...                NaN                  NaN
40913  23/11/2021  1,69134E+15  ...                NaN                  NaN
43066  20/12/2021  1,69134E+15  ...                NaN                  NaN

[1633 rows x 40 columns]

In [ ]:
consolidado_tiktok.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45841 entries, 0 to 685
Data columns (total 40 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               45841 non-null  object
 1   Ad ID                              45841 non-null  object
 2   Cliente                            45841 non-null  object
 3   Ad Name                            45841 non-null  object
 4   Ads Format                         45841 non-null  object
 5   Text                               45841 non-null  object
 6   Ad Group ID                        44208 non-null  object
 7   Ad Group Name                      44208 non-null  object
 8   Campaign ID                        44208 non-null  object
 9   Campaign Name                      44208 non-null  object
 10  Placements Types                   44208 non-null  object
 11  Optimization Goal                  44208 non-null  object
 12  Cost                               44208 non-null  float64
 13  CPC                                44208 non-null  float64
 14  CPM                                44208 non-null  float64
 15  Impression                         44208 non-null  float64
 16  Click                              44208 non-null  float64
 17  CTR                                44208 non-null  float64
 18  Frequency                          44208 non-null  float64
 19  Conversions                        44208 non-null  float64
 20  CPA                                44208 non-null  float64
 21  CVR                                44208 non-null  float64
 22  Video Views                        44208 non-null  float64
 23  2-Second Video Views               44208 non-null  float64
 24  6-Second Video Views               44208 non-null  float64
 25  Video Views at 100%                44208 non-null  float64
 26  Video Views at 75%                 44208 non-null  float64
 27  Video Views at 50%                 44208 non-null  float64
 28  Video Views at 25%                 44208 non-null  float64
 29  Average Watch Time per Video View  44208 non-null  float64
 30  Average Watch Time per Person      44208 non-null  float64
 31  Paid Followers                     44208 non-null  float64
 32  Paid Likes                         44208 non-null  float64
 33  Paid Comments                      44208 non-null  float64
 34  Paid Shares                        44208 non-null  float64
 35  Paid Profile Visits                42575 non-null  float64
 36  Paid Profile Visit Rate            42575 non-null  float64
 37  Anchor Clicks                      42575 non-null  float64
 38  Anchor Clicks Rate                 42575 non-null  float64
 39  Clicks on Music Disc               686 non-null    float64
dtypes: float64(28), object(12)
memory usage: 14.3+ MB

In [ ]:
consolidado_tiktok.head()

         Date        Ad ID  ... Anchor Clicks Rate Clicks on Music Disc
0  22/06/2021  1,70327E+15  ...                0.0                  NaN
1  22/06/2021  1,70327E+15  ...                0.0                  NaN
2  23/06/2021  1,70327E+15  ...                0.0                  NaN
3  23/06/2021  1,70327E+15  ...                0.0                  NaN
4  24/06/2021  1,70327E+15  ...                0.0                  NaN

[5 rows x 40 columns]

In [ ]:
#consolidado_tiktok.to_csv('consolidado_tiktok.csv',sep='\t', encoding="utf-8")
#pd.set_option('float_format', '{:.2f}'.format)

In [ ]:
consolidado_tiktok.to_csv('consolidado_tiktok.csv',float_format='%.f', index=False, header=True)
#df.to_csv('test.out', float_format = '%.2f', index = False, header = False)